### PR TITLE
LRQA-45641 Fix counting of starting new lines on Windows

### PR DESCRIPTION
**Pull request by lesliewong92**
https://issues.liferay.com/browse/LRQA-45641

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:test

**Comment by lesliewong92** [comment]
ci:stop

**Comment by lesliewong92** [comment]
ci:test

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/199

**Pull request closed without merging**
