### PR TITLE
LRQA-45379 & LRQA-45390 Poshi Script fixes

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-45379
https://issues.liferay.com/browse/LRQA-45390

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/185

**Pull request closed without merging**
