### PR TITLE
LRQA-36161 Rename variables and methods in PoshiRunner classes

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-36161

Tested poshi-runner in the following:

legacy poshi tests: 
https://test-5-2.liferay.com//userContent/jobs/legacy-database-dump/builds/22/jenkins-report.html

liferay-portal pullrequest(master):
https://test-5-2.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/89/jenkins-report.html

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:retest

**Comment by yichenroy** [comment]
ci:retest

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/12

@yichenroy Please see my changes in the pull request

**Pull request closed without merging**
