### PR TITLE
LRQA-39880 Retry PoshiRunner when encountering 'Timed out waiting 45 seconds for Firefox to start.'

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-39880

@pyoo47, this is to catch a flaky failure that's been occurring on CI. I'm utilizing the existing poshirunner retry logic to catch another inconsistent issue.

cc-ing: @jpince, @michaelhashimoto

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test

**Comment by kenjiheigel** [comment]
@pyoo47, there's something that changed with the Source Formatter. Somehow this will get caught in portal, but not the subrepo. Looking into this.

**Comment by kenjiheigel** [comment]
ci:test

**Comment by pyoo47** [comment]
@kenjiheigel I got this pull request overnight from Hugo. I think it addresses the SF issues you had.. https://github.com/pyoo47/com-liferay-poshi-runner/pull/27

**Comment by pyoo47** [comment]
@kenjiheigel I've got some issues with the design of the Retry / RetryRule class pairings.. Let's discuss today. I think some small adjustments will make things a bit clearer.

**Comment by kenjiheigel** [comment]
Resent:
https://github.com/pyoo47/com-liferay-poshi-runner/pull/30

**Pull request closed without merging**
