### PR TITLE
LRQA-43588 Remove harcoded implicit timeout setting

### PR DESCRIPTION
**Pull request by lesliewong92**
https://issues.liferay.com/browse/LRQA-43588

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:test

**Comment by lesliewong92** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/158

**Pull request closed without merging**
