### PR TITLE
LRQA-41056,41057,41059,41060 Poshi prose requests

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-41056
https://issues.liferay.com/browse/LRQA-41057
https://issues.liferay.com/browse/LRQA-41059
https://issues.liferay.com/browse/LRQA-41060

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/69

**Pull request closed without merging**
