### PR TITLE
LRQA-35911 Poshi file override (Resend) 

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-35911

Resend of 
https://github.com/pyoo47/com-liferay-poshi-runner/pull/20

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test

**Comment by pyoo47** [comment]
@lesliewong @yichenroy  This seems like there's something wrong in jenkins-ee here.. Can either of you figure out what's going wrong here?

**Comment by yichenroy** [comment]
Sent a pull here for the fix:
https://github.com/pyoo47/liferay-jenkins-ee/pull/672

**Pull request closed without merging**
