### PR TITLE
LRQA-38551 Update Poshi Runner to use FF52

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-38551 

@pyoo47, these are WebDriver 3.0 / Firefox 52 updates. Sending these changes in first so we have it available in upcoming jars. I talked to Leslie and Roy, and we can proceed with adding these changes. We'll update each of the teams dependent on poshi per their needs.

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test

**Comment by pyoo47** [comment]
@yichenroy @lesliewong @kenjiheigel Looks like something is broken in the validation GitHub message logic.

**Comment by yichenroy** [comment]
Sent a pull here for the fix:
https://github.com/pyoo47/liferay-jenkins-ee/pull/672

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/22

**Pull request closed without merging**
