### PR TITLE
LRQA-42956 & LRQA-42019 Add method to get the poshi script line number

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-42956
https://issues.liferay.com/browse/LRQA-42019

Resend of https://github.com/pyoo47/com-liferay-poshi-runner/pull/157

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test

**Comment by pyoo47** [comment]
@kenjiheigel 
```/opt/dev/projects/github/liferay-portal/modules/test/poshi-runner/poshi-runner/src/main/java/com/liferay/poshi/runner/elements/PoshiNode.java:36: error: default methods are not supported in -source 1.7```

Didn't we change to 1.8 for Poshi?

**Comment by kenjiheigel** [comment]
ci:test

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/129

**Pull request closed without merging**
