### PR TITLE
LRQA-45770 Line number interpretation for Poshi description annotation is incorrect

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-45770

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test

**Comment by kenjiheigel** [comment]
ci:test

**Comment by pyoo47** [comment]
@kenjiheigel Can you look into the unit test failures?

**Comment by kenjiheigel** [comment]
The failure appears to be a fluke. The 45 second timeout for Firefox isn't machine related as it would've been caught in verification. Test passes locally. Retriggering the tests to make sure.

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/201

**Pull request closed without merging**
