### PR TITLE
LRQA-44296 Fix unit tests

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-44296

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test

**Comment by kenjiheigel** [comment]
@yichenroy, @lesliewong92 fyi.

**Comment by kenjiheigel** [comment]
ci:test

Committed something by accident earlier.

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/169

**Pull request closed without merging**
