### PR TITLE
LRQA-41058 Add support for 'Table' data structure in PoshiRunner

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-41058

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:test

**Comment by pyoo47** [comment]
Send to myself to test my changes in Pull Request tester. If/When it passes, I'll send to BChan.
https://github.com/pyoo47/com-liferay-poshi-runner/pull/97

@yichenroy Please see my changes in the pull request.

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/83

**Pull request closed without merging**
