### PR TITLE
LRQA-45648 Reformat JSON data in JSONCurlUtil

### PR DESCRIPTION
**Pull request by kevin-yen**
Resubmit of https://github.com/pyoo47/com-liferay-poshi-runner/pull/248
https://issues.liferay.com/browse/LRQA-45648

### CODE REVIEW

**Comment by kevin-yen** [comment]
ci:test

**Comment by kevin-yen** [comment]
ci:test

**Comment by kevin-yen** [comment]
ci:test

**Comment by kevin-yen** [comment]
@pyoo47 I moved the JSON checking code into a separate _isValidJSON method. I also made some minor source formats

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/200

**Pull request closed without merging**
