### PR TITLE
LRQA-44108 Log condition-functions in Poshi summary log

### PR DESCRIPTION
**Pull request by lesliewong92**
https://issues.liferay.com/browse/LRQA-44108

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:test

**Comment by lesliewong92** [comment]
@pyoo47 Cherry-picking SF changes from https://github.com/pyoo47/com-liferay-poshi-runner/pull/210/commits/259acf45d19e331840a935b357203e143ae898fd to pass SF.

**Comment by lesliewong92** [comment]
ci:test

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/165

**Pull request closed without merging**
