### PR TITLE
LRQA-36161 Remove obsolete namespace check in validation

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-36161

We will need a new poshi-runner publication after this pull.

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:stop

**Comment by yichenroy** [comment]
ci:test

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/19

@yichenroy Please see my change in the pull request to BChan.

**Pull request closed without merging**
