### PR TITLE
LPS-77894

### PR DESCRIPTION
**Pull request by petershin**
Please run the CI test after [LPS-77894](https://github.com/brianchandotcom/liferay-portal/pull/55208) is pushed to upstream

### CODE REVIEW

**Comment by pyoo47** [comment]
@kenjiheigel Looks like BChan requested a change to source formatter to get rid of the requirement for  a newline after referencing a variable.

**Comment by pyoo47** [comment]
ci:test

**Comment by petershin** [comment]
A regression bug was introduced in this [commit](https://github.com/liferay/liferay-portal/commit/ffeffe132a351fece7407347d3892c63651d8dda#diff-1a09a7ba955a97f674ba679aeac18445).  :sweat_smile:

Please run the CI test after [LPS-77886](https://github.com/brianchandotcom/liferay-portal/pull/55223) is pushed to upstream

**Comment by petershin** [comment]
ci:stop

**Comment by pyoo47** [comment]
@petershin I'm having a hard time tracking whether or not the necessary fix as been merged in for this. I think it's not ready yet but can you let me know when it is?

**Comment by petershin** [comment]
@pyoo47 - Yup, will let you know

**Comment by petershin** [comment]
ci:test

**Comment by petershin** [comment]
@pyoo47 - Just fyi, looks like this change is already in upstream.

https://github.com/liferay/com-liferay-poshi-runner/commit/3916ab60c3f0606f1146d078c8f830b6363f8e16

**Comment by pyoo47** [comment]
@petershin BChan has applied this change in the past but we always had to revert it because SF was forcing the line to exist. That's why you see it in the history but the blank line is still actually there at HEAD. I'll take care of it from here. Thanks!

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/11

**Pull request closed without merging**
