### PR TITLE
LRQA-43362 Additional changes to change line number logic

### PR DESCRIPTION
**Pull request by lesliewong92**
https://issues.liferay.com/browse/LRQA-43362

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test

**Comment by pyoo47** [comment]
Combined with https://github.com/pyoo47/com-liferay-poshi-runner/pull/178 and retesting here: https://github.com/pyoo47/com-liferay-poshi-runner/pull/179

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/139

**Pull request closed without merging**
