### PR TITLE
 LRQA-41590 Poshi Script initial documentation

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRQA-41590

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test

**Comment by pyoo47** [comment]
@petershin Is this a regression?

**Comment by petershin** [comment]
@pyoo47 yup, will send a patch

just fyi @hhuijser

**Comment by pyoo47** [comment]
ci:test

**Comment by pyoo47** [comment]
ci:test

**Pull request closed without merging**
