### PR TITLE
LRQA-43938 & LRQA-44142 Poshi Script exception handling

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-43938
https://issues.liferay.com/browse/LRQA-44142

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test

**Comment by kenjiheigel** [comment]
ci:test

**Comment by kenjiheigel** [comment]
ci:test

**Comment by kenjiheigel** [comment]
ci:stop

**Comment by kenjiheigel** [comment]
ci:test

**Pull request closed without merging**
