### PR TITLE
LRCI-580 Add syntax for math operators, and fix Poshi Script validation

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-580

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:test

**Comment by kenjiheigel** [comment]
Looking into the failure. I think it was a recent change.

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/240

**Pull request closed without merging**
