### PR TITLE
LRQA-40617 Determine type of 'execute' element by a static list of function files and util classes

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-40617

@christieyoo, this will add multiline support for functions calls in the poshiscript syntax. It should actually add a lot more flexibility across the board when using poshiscript, whether you want to do single/multi line function/macro calls. This will also set up the foundation for [LRQA-40754](https://issues.liferay.com/browse/LRQA-40754).

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test

**Comment by kenjiheigel** [comment]
ci:stop

**Comment by kenjiheigel** [comment]
ci:test

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/53

@kenjiheigel Please note my changes in the pull request

**Pull request closed without merging**
