### PR TITLE
LRQA-43869 Update poshi script java method syntax to use double quotes instead of single quotes

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-43869

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test

**Comment by kenjiheigel** [comment]
ci:stop

**Comment by kenjiheigel** [comment]
ci:test

**Comment by kenjiheigel** [comment]
ci:test

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/160

**Pull request closed without merging**
