### PR TITLE
LRQA-45648 Ignore JSONException since it's expected if data is not a JSON

### PR DESCRIPTION
**Pull request by kevin-yen**
https://issues.liferay.com/browse/LRQA-45648

### CODE REVIEW

**Comment by kevin-yen** [comment]
ci:test

**Comment by pyoo47** [comment]
@kevin-yen What exactly is causing the exception to be thrown?. Is there a way we can handle this situation by preventing the exception instead of ignoring it?

**Comment by kevin-yen** [comment]
ci:test

**Comment by kevin-yen** [comment]
cit:test

**Pull request closed without merging**
