### PR TITLE
LRQA-42657 Add selenium methods to determine if attribute is present in a given element

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-42657

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test

**Comment by pyoo47** [comment]
I've made some changes and sent them back to be tested..
https://github.com/anthony-chu/com-liferay-poshi-runner/pull/1

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/120

**Pull request closed without merging**
