### PR TITLE
LRCI-65 Add PQL query execution command

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRCI-65

Resend of https://github.com/pyoo47/com-liferay-poshi-runner/pull/264

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:test

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/214

**Pull request closed without merging**
