### PR TITLE
LRQA-36161 Use poshi with poshi resource jar

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-36161

This is to work in accordance to the new poshi runner resource jar folder structure I requested:
https://github.com/brianchandotcom/liferay-portal/pull/55471/commits/a735d84b877f4131690100de5ad6af2af52e0c2c

This pull also fixes the issue where test reports are not sending to testray.

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test

**Comment by yichenroy** [comment]
ci:stop

**Comment by yichenroy** [comment]
ci:stop

**Comment by yichenroy** [comment]
ci:test

**Comment by pyoo47** [comment]
Pushed to BChan

https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/17

**Pull request closed without merging**
