### PR TITLE
LRQA-47609 Fix exception message for assert partial text case insensitive

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRQA-47609

Resend of https://github.com/pyoo47/com-liferay-poshi-runner/pull/267

### CODE REVIEW

**Comment by yichenroy** [comment]
ci:test

**Comment by yichenroy** [comment]
I rebased to the latest upstream, going to retest

**Comment by yichenroy** [comment]
ci:test

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/216

**Pull request closed without merging**
