### PR TITLE
LRQA-45514 Add expand/collapse button on Poshi Script log for macros

### PR DESCRIPTION
**Pull request by lesliewong92**
https://issues.liferay.com/browse/LRQA-45514

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:test

**Comment by pyoo47** [comment]
Pushed to BChan
https://github.com/brianchandotcom/com-liferay-poshi-runner/pull/190

**Comment by yichenroy** [comment]
ci:open 

Testing labels

**Comment by yichenroy** [comment]
ci:reopen

**Comment by yichenroy** [comment]
ci:close

**Pull request closed without merging**
